name = "email-forwarder"
main = "src/index.ts"
compatibility_date = "2024-09-18"

[[kv_namespaces]]
binding = "EMAIL_ROUTING"
id = "59bcb707ed274eb6838a21d7d6cef406"

[observability]
enabled = true
head_sampling_rate = 1
